### ISSUE TITLE
vite posthtml doesn't work

### ISSUE THREAD

**Issue by aminya** [chromeos/static-site-scaffold-modules#103]
It gives the following error:

```js
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The property 'options.entryTypes' options.entryTypes can not set with options.type together. Received [ 'measure' ]     
    at new NodeError (node:internal/errors:372:5)
    at PerformanceObserver.observe (node:internal/perf/observe:217:13)
    at posthtmlPlugin (.\node_modules\.pnpm\vite-plugin-posthtml@0.0.3\node_modules\vite-plugin-posthtml\index.js:32:12)
    at file:///C:/test/astro.config.mjs:19:7 {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

**Comment by rossPatton** [comment]
Yeah honestly I wish they would update the docs or provide examples on how to use it. I'm trying to migrate a project and figuring out how the config object needs to be setup is quite frustrating
