### ISSUE TITLE
[eleventy-plugin-local-respimg] SVGs fail to optimize, can't get MIME type.

### ISSUE THREAD

**Issue by x8BitRain** [chromeos/static-site-scaffold-modules#46]
Hey, I'm having an issue with SVGs in the latest version.
Using an `<img src="/images/logos/logo.svg" alt="">` in any HTML causes the following error.

```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: dist/fr/imprint/index.html

`TemplateWriterWriteError` was thrown
> Cannot read property 'mime' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'mime' of undefined
        at Template.respimg (/Users/user/project/node_modules/eleventy-plugin-local-respimg/lib/respimg.js:156:51)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Template.runTransforms (/Users/user/project/node_modules/@11ty/eleventy/src/Template.js:386:13)
        at async Template.renderPageEntry (/Users/user/project/node_modules/@11ty/eleventy/src/Template.js:539:17)
        at async Template.writeMapEntry (/Users/user/project/node_modules/@11ty/eleventy/src/Template.js:547:21)
        at async Promise.all (index 1)
        at async Eleventy.write (/Users/user/project/node_modules/@11ty/eleventy/src/Eleventy.js:428:13)
```

Seems like `const type = await FileType.fromBuffer(file);` in respimg.js is the point of failure as that returns nothing when it's fed an SVG, no idea how to solve.
Thanks!

**Comment by Snugug** [comment]
In a previously closed issue related to this, it was recommended (https://github.com/chromeos/static-site-scaffold-modules/issues/3#issuecomment-685277566) to make sure you include the proper header metadata in your SVG. Can you make sure that's included?

Thanks!

**Comment by x8BitRain** [comment]
Yup, that works.

Adding just `<?xml version="1.0" encoding="utf-8"?>` to the top of the SVGs made it work again. It's a bit strange that it requires that line to work considering most SVGs don't include it, at least the ones I've worked with anyway.

Thanks!
